

services:
  rag_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_api_services
    ports:
      - "8081:8080"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    depends_on:
      - mysql_db
      - qdrant_db
    restart: unless-stopped
    networks:
      - backend

  mysql_db:
    image: mysql:8.0
    container_name: ecommerce_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: rag_chatbot_db
    ports:
      - "3307:3306"
    volumes: 
      - mysql_data:/var/lib/mysql
      # tự động chạy file init.sql khi container khởi tạo lần đầu 
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      # gắn 2 file csv vào container
      - ./data/styles_clean.csv:/var/lib/mysql-files/styles.csv
      - ./data/images_clean.csv:/var/lib/mysql-files/images.csv

    command: --local-infile=1 --sql-mode=""
    restart: unless-stopped
    networks:
      - backend

  qdrant_db:
    image: qdrant/qdrant:latest
    container_name: qdrant_vectoer_db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped
    networks:
      - backend


volumes:
  mysql_data:
  qdrant_storage:


networks:
  backend:
      